#!/usr/bin/php
<?php
$builder = new EmailBuilder();
if($builder->buildEmailVision()){
	die(0);
}
else{
	die(3);
}


class EmailBuilder{
	protected $htmlFile = 'index.html';
	protected $htmlCounter = 0;
	protected $plainFile = 'plain.txt';
	protected $plainCounter = 0;
	protected $settingsFile = 'config/settings.ini';
	protected static $settings = array();

	public function __construct(){
		if(!is_readable($this->settingsFile)){
			throw new Exception("Settings file not readable. Make sure you set it up at config/settings.ini");
		}
		$newSettings = parse_ini_file($this->settingsFile, true);
		foreach($newSettings as $group => $settings){
			if(isset(self::$settings[$group])){
				self::$settings[$group] = array_merge(self::$settings[$group], $settings);
			}
			else{
				self::$settings[$group] = $settings;
			}
		}
	}

	public function setHtmlFile($filename){
		$this->htmlFile = $filename;
	}
	
	public function setPlainFile($filename){
		$this->plainFile = $filename;
	}
	
	protected function replaceHtmlLink($match){
		$newLink = 'href="http://'.$match["url"].'?CMP=EMA-'.self::$settings["email"]["id"].'&CRE='.$this->htmlCounter.'&PLA=html&TYPE=email"';
		$this->htmlCounter++;
		fwrite(STDOUT, 'HTML link ' . $this->htmlCounter . ': ' . $newLink . "\n");
		return $newLink;
	}
	
	protected function replaceTextLink($match){
		$newLink = 'http://'.$match["url"].'?CMP=EMA-'.self::$settings["email"]["id"].'&CRE='.$this->plainCounter.'&PLA=text&TYPE=email';
		$this->plainCounter++;
		fwrite(STDOUT, 'Plain link ' . $this->plainCounter . ': ' . $newLink . "\n");
		return $newLink;
	}
	
	protected function replaceAllLinks($contents, $mode = 'html'){
		$linkTagPattern = '/href="http:\/\/(?P<url>[\w\d\.\/-]+)"/';
		$textLinkPattern = '/http:\/\/(?P<url>[\w\d\.\/-]+)/';
		
		if($mode === 'html'){
			$pattern = $linkTagPattern;
			$callback = 'self::replaceHtmlLink';
		}
		else{
			$pattern = $textLinkPattern;
			$callback = 'self::replaceTextLink';
		}
		
		$contents = preg_replace_callback($pattern, $callback, $contents, -1, $count);
		
		fwrite(STDOUT, 'Total '. $mode . ' links: ' . $count . "\n");
		
		return $contents;
	}
	
	public function buildEmailVision(){
		$stdout = fopen('php://stdout', 'w');
		$html = fopen($this->htmlFile, 'r');
		$plain = fopen($this->plainFile, 'r');
		
		if(file_exists('export/emv.txt')){
			$emv = fopen('export/emv.txt', 'w');
		}
		else{
			mkdir('export', 0755);
			$emv = fopen('export/emv.txt', 'w');
		}
		
		$htmlContents = fread($html, filesize($this->htmlFile));
		$plainContents = fread($plain, filesize($this->plainFile));
		fclose($html);
		fclose($plain);
		
		$htmlContents = $this->replaceAllLinks($htmlContents, 'html');
		$htmlContents = $this->replaceAllLinks($plainContents, 'plain');
		
		fwrite($emv, "[EMV TEXTPART]\n");
		fwrite($emv, $plainContents);
		fwrite($emv, "\n\n");
		fwrite($emv, "[EMV HTMLPART]\n");
		fwrite($emv, $htmlContents);
		fclose($emv);
		return true;
	}
	
}